### PR TITLE
Match button and email width, make button consistent with Bootstrap

### LINKED ISSUE #181: Subscribe button suggestion
This is how the website looks now:
ezgif com-video-to-gif 3
Color change on hover is too drastic also the width of the input and subscribe button are not same, which doesn't seem right.

Ideally, it should be like that in my opinion.
ezgif com-video-to-gif 1

### PR DESCRIPTION
**Pull request by yummypasta**
Fixes #181.
For the email subscribe area, I made the button and input the same width, and changed the button from using Mailchimp styling to the Bootstrap styling.
Screenshot of fixed button

_Note_ Add class _bt_ to the button to make the button rectangular like the other ones. I chose not to do this, as the heights would be different and look strange

### CODE REVIEW

**Comment by yummypasta** [comment]
It is also an easy fix to make them attached. In my opinion, it looks better:
Attached button screenshot

**Comment by quozl** [comment]
Thanks!  Conflicts with https://github.com/sugarlabs/www-sugarlabs/pull/244, please work with each other to come up with a mutually agreed pull request.  i.e. one of you should review and assent to the other pull request, or take the changes into your own pull request.

**Comment by nathan-jacob** [comment]
hey @yummypasta , your idea is great for a future pull request regarding design enhancements, but, for now, just trying to fix the issue 181, I think we should use my pull request because it fixes the basics of the problem, rather than adding on new design elements which would require further approval.

**Comment by yummypasta** [comment]
@nathan-jacob Could you please provide a screenshot of your fix?

**Comment by nathan-jacob** [comment]
screen recording 2018-10-25 at 10 55 46 am

**Comment by yummypasta** [comment]
@quozl I'm going to go ahead and close this PR, I think @nathan-jacob 's is sufficient.

**Pull request closed without merging**
