### PR TITLE
Fix the unclickable slider

### LINKED ISSUE #85: "A glimpse of sugar" carousel button not clickable
image

It seems that the carousel here is different from all the other ones on the page which are clickable. The carousel should have a working navigation so people can view specific images.

### PR DESCRIPTION
**Pull request by kipply**
Fixes #85 

For some reason, this slider wasn't using `owl` like all the other ones. I left the slider nav left aligned in this version, since I thought all the centered text looked a bit off. Thoughts? 

Also most of the line changes are just removing trailing whitespaces, sorry for those of you who are looking at the diff!

### CODE REVIEW

**Comment by kipply** [comment]
image

**Comment by walterbender** [comment]
I am a bit confused as to what is going on here, between the commit that includes formatting changes and the commit that is essentially a rebase to master. Can you please clean this up so that there is one commit -- the one that fixed the problem described?

**Comment by kipply** [comment]
@walterbender should I leave out removal of all the trailing spaces?

**Comment by walterbender** [comment]
Please make just two commits: (1) the changes addressing the issue; (2) the changes to trailing whitespace.

**Comment by kipply** [comment]
I've updated it, sorry for the confusion!

**Comment by kipply** [comment]
@quozl Sorry for the error! It seems that I accidentally deleted a bracket and somehow totally missed that change. I've made a new PR that restores it.

**Comment by quozl** [comment]
Minor regression https://github.com/sugarlabs/www-sugarlabs/issues/358

**Pull request merged**
