### PR TITLE
Added Box-shadow to navbar

### PR DESCRIPTION
**Pull request by Kuthar8055**
I have added the box-shadow to navbar. As you scroll down the page the box-shadow appears under navbar. :)

### CODE REVIEW

**Comment by samswag** [comment]
Can I see an image of the working code? So I will keep note of what changes to look out for.

**Comment by Kuthar8055** [comment]
before
now

**Comment by Kuthar8055** [comment]
The first one shows how it looks before changes and second one shows how it looks after changes

**Comment by quozl** [comment]
Reviewed appearance change.  Assent.

**Comment by amaaniqbal** [comment]
Everything quite good. But changes to nav.html is not required. Also, a few minor modifications are required to vendor prefixes, which I had explained in the GCI task itself.

Go ahead and update your task. Good Luck!

**Comment by quozl** [comment]
Thanks, fixed as of f75484e.

**Comment by quozl** [comment]
@amaaniqbal, please review here.

**Comment by amaaniqbal** [comment]
@Kuthar8055, put vendor prefixes for required stylings in customHeaderStyle2 class too. Then everything will be fine.

**Comment by Kuthar8055** [comment]
In which line Pls! mention @amaaniqbal

**Comment by amaaniqbal** [comment]
In airspace.css, for the box-shadow in line 2679 as I can see in your commit.

**Comment by Kuthar8055** [comment]
Done!!

**Comment by amaaniqbal** [comment]
Reviewed. Thanks!

**Comment by Kuthar8055** [comment]
:) Thanks!!

**Comment by quozl** [comment]
Reviewed in production.  Thanks.

**Pull request merged**
