### PR TITLE
Minimal jQuery scroll to top animation addition. Fix #80

### LINKED ISSUE #80: Add animation for "back to top"
Instead of just jumping to the top, how about scrolling to the top with an animation.

### PR DESCRIPTION
**Pull request by TheOdd**
Fixes #80

Let me know if y'all want anything else or if you needed anything changed from it! Feedback is appreciated! Thanks!

### CODE REVIEW

**Comment by samswag** [comment]
Tested it is working, i will merge PR later.

**Comment by amaaniqbal** [comment]
I see conflicts have been created now. 
@samswag are you going to resolve and merge this or should I create a task for the same in GCI '18?

**Comment by quozl** [comment]
If you can fix it now, we won't have to wait for GCI '18.  :grin:

**Comment by amaaniqbal** [comment]
Okay I am creating a new pull request with same changes.

**Comment by quozl** [comment]
Please rebase following merge of https://github.com/sugarlabs/www-sugarlabs/pull/248.

**Comment by amaaniqbal** [comment]
@quozl this feature has already been implemented in our website in PR #231

**Pull request closed without merging**
