### PR TITLE
Enhanced Profiles Page

### PR DESCRIPTION
**Pull request by S-kus**
I fixed the problem in [this](https://github.com/sugarlabs/www-sugarlabs/pull/347#issuecomment-1013622595). As shown in this [Video](https://drive.google.com/file/d/1UOxaJ7WFAvhgWm81tuwK0KmTmfNikc2a/view?usp=sharing).

- Made page responsive.
- Now **title** and **last updated date** are also showing.
- **Return to main page tag** also present.
- I removed extra padding and made fonts-size similar to other nav-links and fonts.

### CODE REVIEW

**Review by srevinsaju — APPROVED** [review]

**Comment by quozl** [comment]
Added review changes.  As far as I can see, the profile layout wasn't used; can someone else please check for me?

**Comment by srevinsaju** [comment]
> As far as I can see, the profile layout wasn't used
Agreed, I don't see it being used anywhere too. +1 for remove

**Comment by quozl** [comment]
Please use our guide to making commits and make sure the commit messages have the detail that you've been adding to the pull request.

**Comment by S-kus** [comment]
Sorry @quozl, I will be more careful next time.



> can someone else please check for me?

In navbar in the "Join Us" dropdown, it's referred link present as "contributors" and also in the "SugarLabs" section in the footer named as "contributors".

**Comment by quozl** [comment]
Yes, interesting.

**Pull request merged**
