### PR TITLE
Gradients added

### PR DESCRIPTION
**Pull request by abhiskaushik**
In order to make text at glance "Try It Now" & few others, we gave it a gradient, apart added lazy loading to images to improving loading for a given screen size.

### CODE REVIEW

**Comment by SAMdroid-apps** [comment]
I think we could better solve this by adding a sugarizer/soas section.

**Comment by davelab6** [comment]
Should this be closed?

**Comment by davelab6** [comment]
I suggest this can be closed.

**Comment by davelab6** [comment]
Thanks Sam!

**Pull request closed without merging**
