### PR TITLE
Fix dropdown issue #225

### PR DESCRIPTION
**Pull request by amaaniqbal**
This commit enables the dropdown only on click which is the default behaviour with bootstrap dropdown. The custom css which enables the dropdown on hover for screen sizes greater than equal to 767px is removed.

### CODE REVIEW

**Comment by samswag** [comment]
I think you need to review your code as I ran into some errors,
screen shot 2018-09-15 at 2 46 33 pm
 with the navbar you were trying to fix.

**Comment by amaaniqbal** [comment]
Errors? Can you please explain. My pull request only toggles the dropdown on click and not on hover which is the default dropdown behaviour. Is this expected to work in some other way @samswag ?

**Comment by samswag** [comment]
Yes, seeing the image I send the navbar isn't properly position. Did you git pull for updates?

**Comment by amaaniqbal** [comment]
I re-cloned yesterday itself for these pull requests. This is how it appears in my case.

**Comment by quozl** [comment]
Please rebase your branch against our master.

**Comment by amaaniqbal** [comment]
Updated my PR @samswag @quozl . Have a look

**Comment by amaaniqbal** [comment]
Kindly review this too @samswag @quozl

**Comment by samswag** [comment]
I am still seeing that your branch has a conflict.  Would you want to resolve that?

**Comment by amaaniqbal** [comment]
@samswag the conflict was again created since my pull request which you just merged too had modification in airspace.minified file (1 line file). 

Kindly test and merge this. Otherwise again due to some other modification in that css file, the conflict will again get created.

**Comment by quozl** [comment]
@samswag, @amaaniqbal, please consider working on https://github.com/sugarlabs/www-sugarlabs/issues/189 so that these conflicts can be avoided.

**Comment by samswag** [comment]
I think I found a solution to the issue. I will see if I can work on it, @amaaniqbal want to do the honors?

https://medium.com/devux/minifying-your-css-js-html-files-using-gulp-2113d7fcbd16

**Comment by samswag** [comment]
https://www.sitepoint.com/automate-css-tasks-gulp/

**Comment by amaaniqbal** [comment]
Okay, I will work on this.

**Pull request merged**
