### PR TITLE
Add gettingstarted.html

### PR DESCRIPTION
**Pull request by davelab6**
New PR for https://github.com/samdroid-apps/www-sugarlabs/pull/10

### CODE REVIEW

**Comment by samdroid-apps** [comment]
Wait, all of theme comments are from the previous pull request.  Is this different from Daksh's patch?

**Comment by davelab6** [comment]
This is @Daksh 's changeset, you see at the top it says,

> davelab6  wants to merge 5 commits into sugarlabs:master from Daksh:getstarted

**Comment by davelab6** [comment]
@Daksh will you be able to respond to Walter's comments?

**Comment by Daksh** [comment]
@davelab6 I have been away from this code for a long while now and away from programming totally due to academic demands from my school. I am sorry but I do not think that I would be able to help much over here for a long while

**Comment by davelab6** [comment]
@Daksh thanks for following up :)

**Comment by quozl** [comment]
Closing because it will need to be rebased for #67.

**Pull request closed without merging**
