### PR TITLE
Fix carousel and spacing issues

### PR DESCRIPTION
**Pull request by Nepaltechguy2**
This PR should fix issue #75 and center the pagination for the carousel under `A GLIMPSE OF SUGAR...` from left-alignment to centered.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.  #75 was already fixed; the spacing looks fine.

8a0bd822465b5be9847c72bd723d4e14b493dc81 is approved.

Please remove 40dac947fad41ad076fcf296e1f27b01e07855d2 from the pull request, or let me know if you don't know how and I'll cherry-pick 8a0bd822465b5be9847c72bd723d4e14b493dc81.

**Comment by Nepaltechguy2** [comment]
If you could cherry-pick it, that would be great; I don't know how.

**Comment by Nepaltechguy2** [comment]
What tablet are you on? I am on an iPhone with safari and it seems to work, as well as the iPad responsivity tester on Chrome: 

resp

**Comment by quozl** [comment]
iOS 12.1, Safari, on iPad MRJP2X/A.

**Comment by Nepaltechguy2** [comment]
Hmm, I will look into that as soon as I get access to one (likely later today).

**Comment by Nepaltechguy2** [comment]
I looked at it on my iPad, iOS 12, and the carousel buttons were correctly aligned but #75 was not. Was that what you were talking about?

**Comment by quozl** [comment]
No, it was the carousel buttons.  The problem has cleared, therefore it was cache.

```
curl -D - https://sugarlabs.org/css/owl.carousel.css

HTTP/1.1 200 OK
Server: nginx/1.14.0 (Ubuntu)
Date: Thu, 25 Oct 2018 01:57:11 GMT
Content-Type: text/css
Content-Length: 1225
Last-Modified: Wed, 24 Oct 2018 22:20:11 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "5bd0f01b-4c9"
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Cache-Control: max-age=315360000
Strict-Transport-Security: max-age=15768000
Accept-Ranges: bytes

```

**Pull request closed without merging**
