### PR TITLE
search is working

### PR DESCRIPTION
**Pull request by kushagra189**
The search was rectified. There was a problem in google search API.

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed.  I don't understand the change, and there are other changes in the same commit that seem to be whitespace.

**Comment by kushagra189** [comment]
@quozl  basically the google API format was wrong. I haven't added anything but just commented certain "not required" lines. It is working perfectly fine.

**Comment by quozl** [comment]
@kushagra189, thanks for your reply.  I'm the reporter of the issue.

I briefly looked at the Google APIs, but was not able to identify exactly which API is being used, or find why the format was wrong.  I don't understand why you commented certain not required lines.  I don't understand why you didn't remove them instead of comment them.

Several developers like to use `git bisect`, for which unrelated changes cause a lot of problems, so my preference is that commits only change what is intended.  You said the whitespace changes were unintentional; do you intend to remove these changes?

**Comment by quozl** [comment]
@kushagra189, in the pull-request page on GitHub, click on the 'Files Changed' tab to see the aggregate of the commits so far.  That's what I'm looking at to try to understand the change.

If anybody else understands better, don't wait for me to understand, please review.

**Comment by quozl** [comment]
Rebased against master and reverted whitespace changes.  Aggregate change is understandable.  Will squash and merge.

**Pull request merged**
