### PR TITLE
Remove alpha mention on Sugarizer

### PR DESCRIPTION
**Pull request by llaske**
Remove alpha mention on Sugarizer, it's no longer an alpha product :-)

### CODE REVIEW

**Comment by llaske** [comment]
@quozl what's the process to update the website when a PR is merged?
Look like this PR was merged long time ago and still not online.

**Comment by quozl** [comment]
It was automated.  On 6th November I wrote to systems@ (after @tchx84 reported 88bc4f1 had not shown up either), that starting the docker container `freedom:/srv/containers/org.sugarlabs.www-rebuilder` did not seem to work.  I don't know enough about docker yet to figure out what next to check, but my first guess is that operating system upgrade may be connected.

**Comment by llaske** [comment]
@walterbender could you help here? We talked about that to the SLOB meeting yesterday.

**Comment by walterbender** [comment]
I will try to look into it.

**Pull request merged**
