### PR TITLE
Update footer.html

### PR DESCRIPTION
**Pull request by davelab6**
Add twitter follow link

cc @samswag

### CODE REVIEW

**Comment by davelab6** [comment]
cc @samswag

**Comment by samdroid-apps** [comment]
Commit messages please!

**Comment by davelab6** [comment]
What would you prefer?

screen shot 2016-06-11 at 16 54 42

**Comment by samswag** [comment]
@davelab6 @samdroid-apps  did you guys confirm the code to see if it was correct. When is it going to merge?

**Comment by davelab6** [comment]
Its good, merged!

**Comment by samswag** [comment]
I just checked the site using blackberry z10 the twitter follow plugin is not displaying. @davelab6 can u check it out.

**Comment by davelab6** [comment]
On 14 June 2016 at 06:46, Samson Goddy <notifications@github.com> wrote:

> I just checked the site using blackberry z10 the twitter follow plugin is
> not displaying. @davelab6 <https://github.com/davelab6> can u check it
> out.
>
All I can say is that it works for me on a OS X Chrome and Firefox

**Pull request merged**
