### PR TITLE
Fixed link colors issue

### PR DESCRIPTION
**Pull request by angelinag**
Hello!
I made the changes to the color scheme needed.

### CODE REVIEW

**Comment by samswag** [comment]
Sorry, i can't see any changes on the footer, it still looks the same to me. If yours is different could you send me a pic or video?

**Comment by abdulsamad234** [comment]
@angelinag , try using the !important and check if it works

**Comment by angelinag** [comment]
@abdulsamad234 I added the fixes needed.

**Comment by abdulsamad234** [comment]
@angelinag check your task instance on the gci platform.

**Comment by quozl** [comment]
> check your task instance on the gci platform.

20cqvu

Please not to hide anything relevant to pull request?  [Getting Help](https://wiki.sugarlabs.org/go/Google_Code_In_2017/background#Getting_help).

**Comment by walterbender** [comment]
To Quozi's point, the GCI website is not public. Please post the relevant images here as part of the documentation of your change.

**Comment by samswag** [comment]
This branch is probably old, the change isn't very significant. It only changes the highlight color from the existing blue to pink. 

Not in favor with the change.

**Pull request closed without merging**
