### PR TITLE
Change some few things in Sugarlabs website  from Bootstrap3 to Bootstrap4

### PR DESCRIPTION
**Pull request by Joeloedinho**
->First i had to replace the bootstrap.css and bootstrap.js files that are in Bootstrap version 3 to Bootstrap version 4.
->After changing those files, i discovered that all the content in sugarlabs website were no longer centered so i had to center all the content in all different pages that is;
    -->Index page
    -->More
    -->About us
    --->Right down to sugar lesson plan and Sugar stories.

I didn't include all the files of bootstrap version 4, this is because what I was  able to contribute in creating a plan of a suitable approach to achieve Bootstrap4 in Sugarlabs website was just to replace the bootstrap.css and boostrap.js files and adjusting all the contents that needed to be centered.

### CODE REVIEW

**Comment by samswag** [comment]
screenshot 2018-11-15 at 12 00 39 am
screenshot 2018-11-15 at 12 00 46 am

There is alot of bugs with this PR, I will advice you test your changes before sending.

**Comment by samswag** [comment]
Yes, but your PR will not be merge if you break anything like you did.

**Comment by quozl** [comment]
Any news on this, @Joeloedinho?

**Comment by Joeloedinho** [comment]
Yeah I completed the task but it was to document on how to replace
bootstrap 3 to bootstrap 4

**Comment by quozl** [comment]
Thanks.  I'm not involved in GCI.  I'm not asking about the task.  I'm asking about this pull request; are you going to complete this?  If not, it can be closed.

**Comment by Joeloedinho** [comment]
Ok I won't complete the task so it can be close

**Comment by quozl** [comment]
Thanks!

**Pull request closed without merging**
