### PR TITLE
changed the hyperlinks of Get Sugar

### PR DESCRIPTION
**Pull request by S-kus**
Fixes: #342 
Changed the hyperlink of getting SOAS on the website from [installation page](https://wiki.sugarlabs.org/go/Sugar_on_a_Stick/Installation) to the [updated one](https://wiki.sugarlabs.org/go/Sugar_on_a_Stick).

### CODE REVIEW

**Comment by chimosky** [comment]
Reviewed, the idea is to change the `SOAS` link and add one for trisquel too which the hypertext could be 
`Trisquel On A Sugar Toast`.

I think you meant to drop the change in c03bf2c as that creates a conflict.

**Comment by S-kus** [comment]
> I think you meant to drop the change in [c03bf2c](https://github.com/sugarlabs/www-sugarlabs/commit/c03bf2cf6ca2fefe4758065e5b87a37c7d53a075) as that creates a conflict.

Sorry, by mistake I forget to fetch the last commit about changing in Gemfile.lock, I will change this to according to the master branch.

**Comment by S-kus** [comment]
@chimosky Sorry, I am closing this pull request. As because of updates in Gemfile.lock, I needed to update the bundles in my local repository, which just messed with my hyperlinks branch. So I will create a new branch from my master branch and complete this issue properly.

**Comment by chimosky** [comment]
> @chimosky Sorry, I am closing this pull request. As because of updates in Gemfile.lock, I needed to update the bundles in my local repository, which created problems with my hyperlinks branch. So I will create a new branch from my master branch and complete this issue properly.

I understand, you can also solve the issue by resetting the particular commit you don't want and updating your 
local master then rebasing that on the PR branch, it'll look something like this;
```bash
$ git reset c03bf2c --hard
$ git checkout master
$ git pull
$ git checkout hyperlinks
$ git rebase master
```

You can then apply more changes and push when you're ready. Hope that helps!

**Comment by S-kus** [comment]
Okay, I got it. Thank you so much @chimosky, I didn't know this way. I will be careful next time.

**Comment by chimosky** [comment]
> Okay, I got it. Thank you so much @chimosky, I didn't know this way. I will be careful next time.

No need to be careful, we learn everyday and mistakes are fine.

**Pull request closed without merging**
