### PR TITLE
Hide non-functional newsletter

### PR DESCRIPTION
**Pull request by amaaniqbal**
This commit hides the non-functional newsletter for the time being i.e., the lines implementing the newsletter is commented out as decided in #249.

### CODE REVIEW

**Comment by quozl** [comment]
@sugarlabs/a-b and @perriefidelis please review in the context of your project.

**Comment by aperezbios** [comment]
@samswag is this newsletter in fact "non-functional"?

**Comment by perriefidelis** [comment]
Yeah, it's been inactive for a while now. the current design(i.e the one being worked on now) has taken it off. when it become active again we would get it back there

**Comment by quozl** [comment]
But not before we change the style, layout and design of the subscription box several more times?  This pull request is to remove it.  Please be clear if you consent to that.

**Comment by perriefidelis** [comment]
once the newsletter is active, the style and design will be changed. otherwise, yeah I consent to the removal

**Comment by quozl** [comment]
thanks.  found notification for previous comment in my spam folder.

**Pull request merged**
