### PR TITLE
Fix navbar issue #71

### LINKED ISSUE #71: Navbar issues
Noticed the following issues with the navbar on the website:

screenshot at nov 28 11-06-18

* In the desktop view, the text links aren't vertically aligned and are slightly above the center of the navbar.

screenshot at nov 28 11-07-32

* The menu icon in mobile view is located slightly vertically below the center of the navbar.

screenshot at nov 28 11-09-58

* The padding for the menu icon in tablet view is off; it should be slightly to the left and more vertically-aligned towards the center.

### LINKED ISSUE #95: Navbar looks ugly after scrolling down.
image

After adding 3px to padding it looks better. (but not ideal :/)

image

Windows 7, Chrome 62.0.3202.94 (Official Build) (64-bit)
1920x1080

---
(Google Code-In task - artur@motyka.pro)

### PR DESCRIPTION
**Pull request by kipply**
Fixes #71 
Fixes #95 (duplicate issue)
Changes the position of the toggle and sets lower margins for the small navbar.

### CODE REVIEW

**Comment by VatsalBatra** [comment]
I have gone through both #71(dealing with the button alignment ) and #95(the navbar issue) . can I work on this

**Comment by quozl** [comment]
Can this be reviewed by someone please?

**Comment by samswag** [comment]
@quozl I will look at it

**Comment by samswag** [comment]
I did, I didn't notice any changes with the nav bar @kipply could you explain what you did and how you tested the changes?

**Comment by quozl** [comment]
@samswag, thanks for testing.

**Pull request closed without merging**
