### PR TITLE
Sugar Labs website: Modify navbar styling

### PR DESCRIPTION
**Pull request by SzymonLeja**
I think i made it properly :)
Please comment if u have any suggestions

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  I wasn't able to review; not enough information.  More information needed in commit message or pull request; what was the problem to be solved, how was the problem solved, what testing done.  See https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits for ideas.

**Comment by amaaniqbal** [comment]
The exact task was as follows :

"Mostly our website has a very light background(almost white) and our navbar also has a white background. When the page is scrolled, the exact navbar component area is almost invisible.

Add box-shadow to the navbar such that it appears to be floating, distinct and attractive. An example of such a navbar could be found [here](https://in.udacity.com/)."

**Comment by quozl** [comment]
Thanks.  Wasn't that problem fixed in https://github.com/sugarlabs/www-sugarlabs/pull/240?  Can I see before and after screenshot?

**Comment by amaaniqbal** [comment]
It was not any problem. The task just says to make current navbar appear floating and distinctive from rest other components especially for those part of pages where the background is almost white.

**Comment by amaaniqbal** [comment]
@SzymonLeja add a vendor prefix too atleast `-webkit-`. And ensure that box-shadow is present on small and medium sized devices.

Also gradient is current a bit dark. Use 5th argument of box-shadow to give a very light color to the background in rgba format.

**Comment by quozl** [comment]
Thanks.  I disagree with the task; it was probably not widely discussed.  I find the navbar easily recognised before and after scrolling.  So my vote is no.  I'll wait for consensus from the marketing team.  @samswag?

**Comment by samswag** [comment]
@quozl  I tested it isn't solving many problems. I think if the color of the navbar can be changed into something visible compared to the white, then I think that will be a significant change.

For now, I agree with @quozl 
> Thanks. I disagree with the task; it was probably not widely discussed. I find the navbar easily recognised before and after scrolling. So my vote is no. I'll wait for consensus from the marketing team. @samswag?

**Comment by SzymonLeja** [comment]
I just changed the color of the shadow and added webkits. What you think about it?

**Comment by quozl** [comment]
@samswag, thanks.

@SzymonLeja, thanks for your work on this.  I've no time right now to spin up a test instance to see the effect of your change c47368b, but am happy to review a screenshot.

**Comment by SzymonLeja** [comment]
gci
Is it okey?

**Comment by quozl** [comment]
Thanks, I see a drop shadow underneath the navbar.

**Comment by quozl** [comment]
Why close?

**Comment by quozl** [comment]
Thanks.  As a practice, that will make me less willing to review.  No return on the investment of my time.

**Pull request closed without merging**
