### PR TITLE
Fix search bar not properly aligned #214

### PR DESCRIPTION
**Pull request by amaaniqbal**
This commit properly aligns the search box for small screen sizes by forcing left to be 0 using !important so that the javascript cannot toggle it.

### CODE REVIEW

**Comment by samswag** [comment]
I see you have conflicting files on this PR, would you want to look at it?

**Comment by amaaniqbal** [comment]
I juts introduced !important override javascript behavior which is pulling the search box towards left. I can't understand why is it conflicting. Any specific suggestion @samswag ?

**Comment by samswag** [comment]
Here is what I found 

https://github.com/sugarlabs/www-sugarlabs/pull/229/conflicts

**Comment by amaaniqbal** [comment]
The conflict was due to the fact that the minified css file was of just 1 line as expected. So even if there is a minor change, it will create conflict since others might be working on the same. Try running it locally once if you doubt conflict might exist.

**Comment by quozl** [comment]
Please rebase your branch against our master.

We have an outstanding issue to add build process to regenerate minified files from sources.  https://github.com/sugarlabs/www-sugarlabs/issues/189

**Comment by quozl** [comment]
> Did anyone worked on that issue @quozl ?

Why would they tell me??  :grinning:  Even if they did, there is evidently no fix yet, as you had to change a minified file as part of your work on this pull request.  See also our agreed practice of [not asking permission to work on an issue](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md).

> though I hadn't used it before

Nor have I.  You may have to learn.  An opportunity.

**Comment by amaaniqbal** [comment]
> Even if they did, there is evidently no fix yet

Ya I see there is no commit on that pull request. Just asked to know if someone has worked on it in some other issue. 😀

Okay I will update my PR with updated minified file using [gulp minifier](https://www.npmjs.com/package/gulp-minifier).

**Comment by quozl** [comment]
> no commit on that pull request

issue.  :grin:

> will update my PR with updated minified file using gulp minifier.

No, for this PR, just resolve the conflicts, using a minimal change so that it can be reviewed.

Let's not use this PR for https://github.com/sugarlabs/www-sugarlabs/issues/189

**Comment by amaaniqbal** [comment]
> issue. 😁

Oh sorry

> No, for this PR, just resolve the conflicts, using a minimal change so that it can be reviewed.

I only added a CSS overrider !important in one CSS styling and that created the conflict. So do you mean I should compress my normal CSS file using gulp minifier or something else?

**Comment by quozl** [comment]
> I only added a CSS overrider !important in one CSS styling and that created the conflict.

No, the conflict was created because your branch is out of date, and the _master_ branch has since moved forward by a few commits, and these commits conflict with yours.  Have a look at;

* [our _master_ branch](https://github.com/sugarlabs/www-sugarlabs/commits/master) which shows latest commit is a83e83e,
* [your _search-align_ branch](https://github.com/amaaniqbal/www-sugarlabs/commits/search-align) which shows some merging on top of what our _master_ branch was at the time you began working on this, i.e. b7a557a5085bd44940917cf08daea663f4120ece

You might `git fetch` from both repositories and then use a visualiser like `gitk --all` to see the history of commits in relation to each other.

Previous advice on this type of scenario may be of help;
* [keep your pull request up to date](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#keep-your-pull-request-up-to-date).

**Comment by amaaniqbal** [comment]
> No, the conflict was created because your branch is out of date, and the master branch has since moved forward by a few commits, and these commits conflict with yours.

Sorry I didn't get it previously.

Hope this commit resolves the issue. Thanks @quozl

**Comment by amaaniqbal** [comment]
Is something still lacking in this PR @samswag @quozl ?

**Comment by samswag** [comment]
@amaaniqbal I am away from my computer for the next 3 hours. After that, I will review the code. Maybe @quozl can review while I am still AFK for 3 hours.

**Comment by quozl** [comment]
I’m away from my desk too.  Happy to explain why I haven’t merged; it’s all about ambiguity;

* GItHub doesn’t show the change to the minified file, so I’d have to check that using a word diff program, and I don’t have one handy on the device I’m using today ... hence why a fix to #189 would be so useful to us,
* your commit doesn’t say why the change is made; I can see the use of `!important`, but I’m not sure why.

**Comment by amaaniqbal** [comment]
@quozl left positioning is toggled using javascript. Because of that search box is shifted too much towards left for small devices. And to overcome it I used `!important` overrider.

**Comment by samswag** [comment]
tested

**Pull request merged**
