### PR TITLE
Removed 'modernizr'

### PR DESCRIPTION
**Pull request by S-kus**
Fixes: #352 

- deleted 'modernizr.min.js'
- removed referred script link of 'modernizr.min.js' from footer.html
- updated 'LicenseInformation.txt' as modernizr is not in use and also corrected the numbering.

### CODE REVIEW

**Comment by quozl** [comment]
Modernizr also adds classes on the `<html>` element.  Does our site use them?

**Comment by S-kus** [comment]
@quozl I have gone through the code for this and I didn't get any problem on my local server of the site after removing the modernizer.

**Comment by S-kus** [comment]
No @quozl, I have not found any `<html>` classes and I have tested in **Chrome Version 96.0.4664.45** and **Firefox v96.0**. So I am not sure about older browsers.

**Comment by quozl** [comment]
Thanks.  How did you check for classes on the `<html>` element?

**Comment by S-kus** [comment]
> Thanks. How did you check for classes on the `<html>` element?

Firstly, I have read the modernizr.min.js Modernizer Documents and its official GitHub code source, see how to use them and their functions, then I search for those keywords and functions in the whole code base with the help of VScode, so that I get any classes or functions related to it. Other than this, After removing the file and referring links, I also went through the site to see if any links or functions are broken or not.

**Comment by quozl** [comment]
Thanks.  I've learned something.  Rebased.  Rewrote commit message.

**Comment by S-kus** [comment]
> Rebased. Rewrote commit message.

Thank you @quozl, I was also rebasing it with the master branch and working on the conflicts and just found out you have done this already.

**Comment by quozl** [comment]
No worries, I enjoy git conflict resolution, it is good practice.  Our [Guide for Reviewers](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#guide-for-reviewers) says "_not waste the time of the contributor, by doing anything trivial that otherwise the contributor might have to do._"

Try some reviewing yourself.  :grin:

**Pull request merged**
