### PR TITLE
footer center fixed

### PR DESCRIPTION
**Pull request by sanatankc**

### CODE REVIEW

**Comment by sanatankc** [comment]
Oh! formatting fix were not intentional, my editor automatically fixed them for me.

**Comment by sanatankc** [comment]
Should I discard them?

**Comment by walterbender** [comment]
Please make a separate pull request with the formatting changes.

**Comment by abdulsamad234** [comment]
And can you include screenshots please? @sanatankc

**Comment by sanatankc** [comment]
I have made requested changes in https://github.com/sugarlabs/www-sugarlabs/pull/116

**Pull request closed without merging**
