### PR TITLE
Improve of side social buttons style - suggestion [GCI] #171

### PR DESCRIPTION
**Pull request by kanishkarj**
As per the discussion on pr #171 , I styled the social media buttons. this is how it looks now :
screenshot from 2018-03-11 19-28-59

### CODE REVIEW

**Comment by quozl** [comment]
I've reviewed the change but I do not understand it.

* [ ] there are changes to trailing whitespace in base.html; are these necessary or accidental?
* [ ] social-share-kit.css was changed from one line to many, making it impossible to see the actual changes (if any) in git diff shown by github,
* [ ] a new minified file is added, which we've already seen in recent pull requests is adding to maintenance costs, re #189.

**Comment by kanishkarj** [comment]
@quozl Ill address each of these issues one by one:

- [ ] they are not necessary, they are accidental. I have changed the Stylesheet link in base.html to the minified file, maybe while doing that I left some whitespaces.

- [ ] The thing is social-share-kit.css is a minified CSS file by itself. I don't find it wise in editing a minified CSS file. As CSS by itself is hard to understand and minifying it makes it worse. Hence I made a separate minified file so that the changes can be made to social-share-kit.css and then minified to social-share-kit.min.css.  

- [ ] Yes I have seen that issue before. I think its more efficient to have a minified file. And I can write a proper gulp process to minify files appropriately, in fact, I was working on it without realizing someone has done that.  

Please let me know if you want me to edit the minified file itself, or if you want me to leave it like this and write a gulp process.

**Comment by quozl** [comment]
Thanks.  But as nothing about the change has changed since eb3c034, I still don't understand it.  Is it necessary to change the file between minified and not-minified in order to fix the problem?

**Comment by kanishkarj** [comment]
Actually, it's not required. I can put back just the minified file. But think of it like this, every time someone wants to edit the styles file they will have to beautify the code, make changes and then minify it back.
But what if we could make changes and the gulp process takes care of the rest. easier right!

the changes can be seen in the GUI, notice the sidebar : 
before:
screenshot from 2018-03-12 12-24-19

After:
screenshot from 2018-03-11 19-28-59

**Comment by quozl** [comment]
What did you change?

**Comment by kanishkarj** [comment]
I changed CSS. and the stylesheet path in HTML to the minified file. in CSS i added styles for ssk-facebook and the rest

**Comment by quozl** [comment]
But I can't see the change in the commits.  I can only see the files after you've made multiple changes.  So my review is blocked.

**Comment by kanishkarj** [comment]
So what changes am I supposed to do?

**Comment by quozl** [comment]
You've made too many changes at once, so reviewers cannot see easily and exactly which change fixed the problem #171.

You might split your commit into several.

**Comment by kanishkarj** [comment]
Ahh, shall work on that. Thank you

**Comment by kanishkarj** [comment]
Hey! Ill close this Pull request and open a cleaner one. Thanks

**Pull request closed without merging**
