### PR TITLE
Update contributor profile

### PR DESCRIPTION
**Pull request by pro-panda**
Added [Rahul Bothra's](http://github.com/Pro-Panda) profile on Contributor's page

### CODE REVIEW

**Comment by chimosky** [comment]
@Pro-Panda, have you considered applying for [membership](https://wiki.sugarlabs.org/go/Sugar_Labs/Members#Applying_for_membership)?

**Comment by quozl** [comment]
I don't think membership is a requirement for merging this pull request.  I'm not a member.

**Comment by chimosky** [comment]
> I don't think membership is a requirement for merging this pull request. I'm not a member.

It's not, I was making a suggestion.

**Comment by pro-panda** [comment]
@samswag Please review

**Pull request merged**
