### PR TITLE
'daivd' to 'david' typo correction

### PR DESCRIPTION
**Pull request by deejoe**

### CODE REVIEW

**Comment by chimosky** [comment]
There's two occurences of the typo, you corrected only one.

**Comment by deejoe** [comment]
On Tue, Mar 20, 2018 at 06:58:57AM -0700, Ibiam Chihurumnaya wrote:
> There's two occurences of the typo, you corrected only one.

That may be correct, but it's neither welcoming nor constructive.

I submitted the patch for the typo I found, as I found it.

A constructive response would be something like:

"Thank you for your patch. I have found a second instance of the same typo," followed by your own pull
request fixing both.

If you would like to learn more about submitting patches of your own, please
let us know.

**Comment by chimosky** [comment]
Noted.

**Comment by quozl** [comment]
@chimosky, an easy mistake to make in haste, you may be interested in [Guide for Reviewers](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#guide-for-reviewers).

**Comment by quozl** [comment]
Thanks!

**Pull request merged**
