### PR TITLE
Remove unused CSS

### PR DESCRIPTION
**Pull request by amaaniqbal**
This commit removed some unused CSS as pointed in a GCI task.

### CODE REVIEW

**Comment by quozl** [comment]
As _airspace.css_ is from an upstream project, there's good reason to stay synchronised, and not enough reason to desynchronise further.  The amount saved is trivial compared to the size of the cold cache page load.  So my vote is no.

**Comment by amaaniqbal** [comment]
I agree with you. It's best to stay synchronized with the upstream unless there is a strong reason to desynchronize. I just wish to send the work of a GCI student. Also, there are three instances of this task and only two was completed. One was this and the other was #263.

**Comment by quozl** [comment]
I'm not surprised.  GCI tasks are often hastily prepared and not reviewed.  Often it is only when the pull request arrives that actual review takes place.  Ignore GCI, and concentrate on the legitimacy of the proposed change?

**Comment by amaaniqbal** [comment]
Then I think this should be closed.

**Pull request closed without merging**
