### PR TITLE
Fixes #181

### LINKED ISSUE #181: Subscribe button suggestion
This is how the website looks now:
ezgif com-video-to-gif 3
Color change on hover is too drastic also the width of the input and subscribe button are not same, which doesn't seem right.

Ideally, it should be like that in my opinion.
ezgif com-video-to-gif 1

### PR DESCRIPTION
**Pull request by nathan-jacob**
Fixes Button sizing below the newsletter text box, fixes color gradient change

### CODE REVIEW

**Comment by nathan-jacob** [comment]
This fixes everything listed in the issue #181, feel free to comment with any additional changes necessary.

**Comment by quozl** [comment]
Thanks!  Conflicts with https://github.com/sugarlabs/www-sugarlabs/pull/243, please work with each other to come up with a mutually agreed pull request.  i.e. one of you should review and assent to the other pull request, or take the changes into your own pull request.

**Comment by nathan-jacob** [comment]
@quozl we resolved the conflict and decided to go with mine, see pull #243 (now closed) for more info.

**Comment by quozl** [comment]
Thanks.  Reviewed.  I approve the change except the minified file has more change than the source file; something others are working on in https://github.com/sugarlabs/www-sugarlabs/pull/190 and https://github.com/sugarlabs/www-sugarlabs/pull/236

Can you check again that the minified file was correctly processed by your local tools?  When compared with diff it looks like the ordering was changed.

**Comment by nathan-jacob** [comment]
Fixed the minifier issue

**Comment by quozl** [comment]
Thanks.  I've checked as at b66f95e, but it doesn't look like a simple change.

Have a go at it yourself; the output of these two commands should be very similar;

```
git diff --word-diff=color master -- css/airspace.css
git diff --word-diff=color master -- css/airspace.minified.css
```

But at the moment the minified file has many extra changes, probably re-ordering.

**Comment by nathan-jacob** [comment]
Done, thank you for your time.

**Comment by quozl** [comment]
Reviewed in production, looks fine.  Firefox 62.0.3.  Safari on iOS 12.1.  Noted that pressing submit without entering an address redirects to list-manage.com, a service we aren't in control of as far as I know.

**Pull request merged**
